language: node_js
node_js:
  - "7"
branches:
  only:
    - master
env:
  global:
  - "FTP_USER=fagrano_todo"
  - "FTP_PASSWORD=agranom777"

before_script:
  - npm install -g @angular/cli

script:
  - ng build

install:
  - "echo $FTP_USER"
  - npm install
  - npm build
after_success:
  -  "curl --ftp-create-dirs -T /dist/*.ico -u $FTP_USER:$FTP_PASSWORD ftp://fagrano.beget.tech/"
