language: node_js
node_js:
  - "7"
branches:
  only:
    - master
env:
  global:
  - FTP_USER=fagrano_todo
  - FTP_PASS=28Hu

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

install:
  - "echo $FTP_USER"
  - npm install
  - npm build
after_success:
  - ./deploy.sh
